### ISSUE TITLE
Duplicate posts created

### ISSUE THREAD

**Issue by vadi2** [Mudlet/mudlet-release-plugin#4]
Somehow every language got many duplicate posts created that required cleanup:

![Screenshot 2023-03-19 at 13-44-52 Posts ‹ Mudlet — WordPress](https://user-images.githubusercontent.com/110988/226176334-c5ddc394-ab7c-4ee2-843a-91b70402834a.png)

**Comment by Delwing** [comment]
![image](https://user-images.githubusercontent.com/3740628/226993154-a49b0ba3-5420-47f9-938f-f34f8fb47d9b.png)
I think this is an issue - 3 events published at the same time, so each one made release webhook run concurrently - getting release posts for all 3 resulted in 0 results.
